### ISSUE TITLE
为什么没有生成yolo_nnie 文件

### ISSUE THREAD

**Issue by yzl1014** [wllkk/yolov5-nnie#2]
我按照你的编译步骤编译，没有报错，但是也没有生成nnie文件

**Comment by wllkk** [comment]
> 我按照你的编译步骤编译，没有报错，但是也没有生成nnie文件

cmake之后要 执行 make 指令的。你执行了吗？

**Comment by yzl1014** [comment]
您好，有没有原始的yolov5 生成的wk文件呢？就是在coco上面的训练文件。

**Comment by wllkk** [comment]
> 您好，有没有原始的yolov5 生成的wk文件呢？就是在coco上面的训练文件。

之前生成过，但是现在已经删掉了。你可以根据教程自己生成一个。

**Comment by yzl1014** [comment]
您能直接上传马？

**Comment by wllkk** [comment]
> 您能直接上传马？

不好意思啊，我说的就是本地。我这边也没有了

**Comment by yzl1014** [comment]
那我生成的wk 文件可以直接在 这个代码里面运行马？用不用代码里面修改？

**Comment by wllkk** [comment]
> 那我生成的wk 文件可以直接在 这个代码里面运行马？用不用代码里面修改？

改一下yolo_post.h里的类别就行。如果anchor变了，还要改一下anchor值。其它的应该就不用改了。

**Comment by yzl1014** [comment]
那个参考文档写的都是大概阿，不好复现

**Comment by yzl1014** [comment]
就没有完整流程

**Comment by wllkk** [comment]
> 就没有完整流程
基本流程就是在yolov5代码里用卷积替换focus层，然后再按照博客里面的，移除permute层，然后修改reshape层就行了。上采样层可以不用修改。
