### ISSUE TITLE
你好确认一下，能确认一下模型么？

### ISSUE THREAD

**Issue by sunbinbin1991** [wllkk/yolov5-nnie#6]
1：当前转换wk的caffe模型是否是来源如下两个模型
![image](https://user-images.githubusercontent.com/15342883/145352052-3d71722e-51e7-4853-b72c-a5fa599b8fa3.png)
2：当前转换的wk模型输入是rgb格式的么？

**Comment by wllkk** [comment]
1、models文件夹中的inst_yolov5s_nofocus_decon_rgb.wk是用你图中的这个not-focus-deconv.caffemodel转换的。
2、数据输入格式是rgb。

**Comment by sunbinbin1991** [comment]
@wllkk 多谢
