### ISSUE TITLE
耗时时间有异常

### ISSUE THREAD

**Issue by StarvenLan** [wllkk/yolov5-nnie#7]
请问您总体的时间消耗有多少啊？我分别是12ms，42ms，2s，后处理2s好像有点问题

**Comment by wllkk** [comment]
> 请问您总体的时间消耗有多少啊？我分别是12ms，42ms，2s，后处理2s好像有点问题

我测试着挺正常，可能种类比较少。你可以分别打印一下后处理部分函数耗时，找一下问题٩(๑•̀ω•́๑)۶

**Comment by StarvenLan** [comment]
不知道您后处理大概多少😭我好有个参考

**Comment by StarvenLan** [comment]
已经解决了
